// action - customization reducer
export const SET_MENU = '@customization/SET_MENU';
export const MENU_TOGGLE = '@customization/MENU_TOGGLE';
export const MENU_OPEN = '@customization/MENU_OPEN';
export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY';
export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS';
export const SHIFT_ADD = '@customization/SHIFT_ADD';
export const SHIFT_UPDATE = '@customization/SHIFT_UPDATE';
export const SHIFT_DELETE = '@customization/SHIFT_DELETE';
export const DEPARTMENT_UPDATE = '@customization/DEPARTMENT_UPDATE';
export const DEPARTMENT_ADD = '@customization/DEPARTMENT_ADD';
export const DEPARTMENT_DELETE = '@customization/DEPARTMENT_DELETE';
export const NURSE_DELETE = '@customization/NURSE_DELETE';
export const NURSE_ADD = '@customization/NURSE_ADD';
export const NURSE_UPDATE = '@customization/NURSE_UPDATE';
